### ISSUE TITLE
[Block Type] Rating Page List

### ISSUE THREAD

**Issue by hissy** [concrete5cojp/c5j_ratings#1]
* Controller: Almost same as Page List but has additional filters & orders
    * filter by "rated by me"
    * filter by number of rated (e.g., show pages rated by at least ten users only). Enable to set 0
    * sort by "most rated."
* View: compatible with page list block template, but can display rating count 
* No need to implement these page list block features
    * RSS

**Comment by hissy** [comment]
Add an ability to show rating button on each page s displaced by this block

**Comment by biplobice** [comment]
Should be fixed in https://github.com/concrete5cojp/c5j_ratings/pull/5
