### ISSUE TITLE
Concrete CMS v9 compatibility

### ISSUE THREAD

**Issue by biplobice** [concrete5cojp/c5j_ratings#20]
When you try to edit a `Rating Page List` block you'll get the following error-

```
Call to undefined method Concrete\Core\Application\Service\Urls::getBlockTypeToolsURL()
```

Please check the following references to fix this issue.
- https://github.com/concretecms/concretecms/pull/8976
- https://github.com/concretecms/concretecms/commit/1f9396246880b0b2d94256b7040ee8ab249ff191

**Comment by biplobice** [comment]
@moriaiy 
It's supposed to work with v9. Can you please confirm?

**Comment by moriaiy** [comment]
@biplobice 
I ran it on version 9.
There seems to be no problem.
