### ISSUE TITLE
Rating Blocks not counting ratings.

### ISSUE THREAD

**Issue by leal-k** [concrete5cojp/c5j_ratings#35]
Concrete **v9.3.4**
PHP **v8.3**
Macareux Ratings **v.1.0.1**

When a rating block is put on the website, and you click it, the rating number does not go up, but it stays static at 0.
The table `btC5jRatings` is updated with all the Rating Buttons that are put on the website, same with the table `btC5jRatingPageList`, it is updated with all the Rating Page Lists you put on the website.
But the table `C5jRatings` does not register anything, it stays empty even though the rating buttons and rating page lists are clicked.

**Comment by biplobice** [comment]
@SashaMcr 
Could you please confirm this issue? I think you had resolved it previously.

**Comment by SashaMcr** [comment]
@biplobice 

it works as expected

@leal-k 
Is it problem on some project or on clear project?

**Comment by leal-k** [comment]
I just replied to Biplob on the other conversation, on fix #34 , explaining the whole bug and fixes, but basically I was getting this error when I fixed the array to string conversion. When I updated the SQL query both bugs disappeared, and the counts were being stored, as I commented on fix #36 .

**Comment by biplobice** [comment]
@leal-k 
Cc: @SashaMcr 
If this issue isn't valid anymore, please feel free to close the issue and the PR.
